spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/training_service
    username: root
    password: IT0677627052

  jpa:
   show-sql: true
   hibernate:
    ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml