spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/training_service
    username: root
    password: IT0677627052

  jpa:
    show-sql: false
    ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    parameters:
      searchPath: classpath:/db/changelog/changes/v0.0.1-SNAPSHOT/
    enabled: true


Swagger configuration:
  springfox:
    documentation:
      swagger-ui:
        path: /swagger-ui/index.html

  app:
    description: Training service
    version: 1.0.0
    server:
      url: http://localhost:8080
      stage: development

token:
  signing:
    key: 1d770d10e025ee9c1918bb89bcfb2c45c77f966e26171365be2d0ad99d32c814