spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/training_service
    username: root
    password: IT0677627052

  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    #hibernate:
    ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
 #   change-log: classpath:/db/changelog/changes/v0.0.1-SNAPSHOT/master-changelog.xml
    parameters:
      searchPath: classpath:/db/changelog/changes/v0.0.1-SNAPSHOT/
    enabled: true


Swagger configuration:
 springfox:
   documentation:
  #swagger.v2.path=/api-docs
     swagger-ui:
       path: /swagger-ui/index.html

 app:
   description: Training service
   version: 1.0.0
   server:
     url: http://localhost:8080
     stage: development

variables:
  jwtSecret: 749fe06c2d935dd3d9540498a5ada866ec421696764cdcfdb6766b2e824d35c3
  jwtExpirationMS: 864_000_000


# <!-- app:
#    server:
#      url: http://localhost:8080-->