DROP TABLE IF EXISTS LOCATIONS;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS RATINGS;
DROP TABLE IF EXISTS TYPES_OF_LEARNING;
DROP TABLE IF EXISTS SERVICES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS DIRECTIONS;